{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chirpstack.fullname" . }}-postgres
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
{{- end }}
