FROM ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:latest

RUN apt-get update && \
    apt-get --assume-yes install \
    curl

ENV PB_REL="https://github.com/protocolbuffers/protobuf/releases"
RUN curl -LO $PB_REL/download/v26.1/protoc-26.1-linux-x86_64.zip && unzip protoc-26.1-linux-x86_64.zip -d / && mv /include /bin/
