// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Modulation int32

const (
	// LoRa
	Modulation_LORA Modulation = 0
	// FSK
	Modulation_FSK Modulation = 1
	// LR-FHSS
	Modulation_LR_FHSS Modulation = 2
)

// Enum value maps for Modulation.
var (
	Modulation_name = map[int32]string{
		0: "LORA",
		1: "FSK",
		2: "LR_FHSS",
	}
	Modulation_value = map[string]int32{
		"LORA":    0,
		"FSK":     1,
		"LR_FHSS": 2,
	}
)

func (x Modulation) Enum() *Modulation {
	p := new(Modulation)
	*p = x
	return p
}

func (x Modulation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modulation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (Modulation) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x Modulation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modulation.Descriptor instead.
func (Modulation) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

type Region int32

const (
	// EU868
	Region_EU868 Region = 0
	// US915
	Region_US915 Region = 2
	// CN779
	Region_CN779 Region = 3
	// EU433
	Region_EU433 Region = 4
	// AU915
	Region_AU915 Region = 5
	// CN470
	Region_CN470 Region = 6
	// AS923
	Region_AS923 Region = 7
	// AS923 with -1.80 MHz frequency offset
	Region_AS923_2 Region = 12
	// AS923 with -6.60 MHz frequency offset
	Region_AS923_3 Region = 13
	// (AS923 with -5.90 MHz frequency offset).
	Region_AS923_4 Region = 14
	// KR920
	Region_KR920 Region = 8
	// IN865
	Region_IN865 Region = 9
	// RU864
	Region_RU864 Region = 10
	// ISM2400 (LoRaWAN 2.4 GHz)
	Region_ISM2400 Region = 11
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0:  "EU868",
		2:  "US915",
		3:  "CN779",
		4:  "EU433",
		5:  "AU915",
		6:  "CN470",
		7:  "AS923",
		12: "AS923_2",
		13: "AS923_3",
		14: "AS923_4",
		8:  "KR920",
		9:  "IN865",
		10: "RU864",
		11: "ISM2400",
	}
	Region_value = map[string]int32{
		"EU868":   0,
		"US915":   2,
		"CN779":   3,
		"EU433":   4,
		"AU915":   5,
		"CN470":   6,
		"AS923":   7,
		"AS923_2": 12,
		"AS923_3": 13,
		"AS923_4": 14,
		"KR920":   8,
		"IN865":   9,
		"RU864":   10,
		"ISM2400": 11,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[1].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[1]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

type FType int32

const (
	// JoinRequest.
	FType_JOIN_REQUEST FType = 0
	// JoinAccept.
	FType_JOIN_ACCEPT FType = 1
	// UnconfirmedDataUp.
	FType_UNCONFIRMED_DATA_UP FType = 2
	// UnconfirmedDataDown.
	FType_UNCONFIRMED_DATA_DOWN FType = 3
	// ConfirmedDataUp.
	FType_CONFIRMED_DATA_UP FType = 4
	// ConfirmedDataDown.
	FType_CONFIRMED_DATA_DOWN FType = 5
	// RejoinRequest.
	FType_REJOIN_REQUEST FType = 6
	// Proprietary.
	FType_PROPRIETARY FType = 7
)

// Enum value maps for FType.
var (
	FType_name = map[int32]string{
		0: "JOIN_REQUEST",
		1: "JOIN_ACCEPT",
		2: "UNCONFIRMED_DATA_UP",
		3: "UNCONFIRMED_DATA_DOWN",
		4: "CONFIRMED_DATA_UP",
		5: "CONFIRMED_DATA_DOWN",
		6: "REJOIN_REQUEST",
		7: "PROPRIETARY",
	}
	FType_value = map[string]int32{
		"JOIN_REQUEST":          0,
		"JOIN_ACCEPT":           1,
		"UNCONFIRMED_DATA_UP":   2,
		"UNCONFIRMED_DATA_DOWN": 3,
		"CONFIRMED_DATA_UP":     4,
		"CONFIRMED_DATA_DOWN":   5,
		"REJOIN_REQUEST":        6,
		"PROPRIETARY":           7,
	}
)

func (x FType) Enum() *FType {
	p := new(FType)
	*p = x
	return p
}

func (x FType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[2].Descriptor()
}

func (FType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[2]
}

func (x FType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FType.Descriptor instead.
func (FType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

type MacVersion int32

const (
	MacVersion_LORAWAN_1_0_0 MacVersion = 0
	MacVersion_LORAWAN_1_0_1 MacVersion = 1
	MacVersion_LORAWAN_1_0_2 MacVersion = 2
	MacVersion_LORAWAN_1_0_3 MacVersion = 3
	MacVersion_LORAWAN_1_0_4 MacVersion = 4
	MacVersion_LORAWAN_1_1_0 MacVersion = 5
)

// Enum value maps for MacVersion.
var (
	MacVersion_name = map[int32]string{
		0: "LORAWAN_1_0_0",
		1: "LORAWAN_1_0_1",
		2: "LORAWAN_1_0_2",
		3: "LORAWAN_1_0_3",
		4: "LORAWAN_1_0_4",
		5: "LORAWAN_1_1_0",
	}
	MacVersion_value = map[string]int32{
		"LORAWAN_1_0_0": 0,
		"LORAWAN_1_0_1": 1,
		"LORAWAN_1_0_2": 2,
		"LORAWAN_1_0_3": 3,
		"LORAWAN_1_0_4": 4,
		"LORAWAN_1_1_0": 5,
	}
)

func (x MacVersion) Enum() *MacVersion {
	p := new(MacVersion)
	*p = x
	return p
}

func (x MacVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MacVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[3].Descriptor()
}

func (MacVersion) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[3]
}

func (x MacVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MacVersion.Descriptor instead.
func (MacVersion) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

type RegParamsRevision int32

const (
	RegParamsRevision_A           RegParamsRevision = 0
	RegParamsRevision_B           RegParamsRevision = 1
	RegParamsRevision_RP002_1_0_0 RegParamsRevision = 2
	RegParamsRevision_RP002_1_0_1 RegParamsRevision = 3
	RegParamsRevision_RP002_1_0_2 RegParamsRevision = 4
	RegParamsRevision_RP002_1_0_3 RegParamsRevision = 5
	RegParamsRevision_RP002_1_0_4 RegParamsRevision = 6
)

// Enum value maps for RegParamsRevision.
var (
	RegParamsRevision_name = map[int32]string{
		0: "A",
		1: "B",
		2: "RP002_1_0_0",
		3: "RP002_1_0_1",
		4: "RP002_1_0_2",
		5: "RP002_1_0_3",
		6: "RP002_1_0_4",
	}
	RegParamsRevision_value = map[string]int32{
		"A":           0,
		"B":           1,
		"RP002_1_0_0": 2,
		"RP002_1_0_1": 3,
		"RP002_1_0_2": 4,
		"RP002_1_0_3": 5,
		"RP002_1_0_4": 6,
	}
)

func (x RegParamsRevision) Enum() *RegParamsRevision {
	p := new(RegParamsRevision)
	*p = x
	return p
}

func (x RegParamsRevision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegParamsRevision) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[4].Descriptor()
}

func (RegParamsRevision) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[4]
}

func (x RegParamsRevision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegParamsRevision.Descriptor instead.
func (RegParamsRevision) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

type LocationSource int32

const (
	// Unknown.
	LocationSource_UNKNOWN LocationSource = 0
	// GPS.
	LocationSource_GPS LocationSource = 1
	// Manually configured.
	LocationSource_CONFIG LocationSource = 2
	// Geo resolver (TDOA).
	LocationSource_GEO_RESOLVER_TDOA LocationSource = 3
	// Geo resolver (RSSI).
	LocationSource_GEO_RESOLVER_RSSI LocationSource = 4
	// Geo resolver (GNSS).
	LocationSource_GEO_RESOLVER_GNSS LocationSource = 5
	// Geo resolver (WIFI).
	LocationSource_GEO_RESOLVER_WIFI LocationSource = 6
)

// Enum value maps for LocationSource.
var (
	LocationSource_name = map[int32]string{
		0: "UNKNOWN",
		1: "GPS",
		2: "CONFIG",
		3: "GEO_RESOLVER_TDOA",
		4: "GEO_RESOLVER_RSSI",
		5: "GEO_RESOLVER_GNSS",
		6: "GEO_RESOLVER_WIFI",
	}
	LocationSource_value = map[string]int32{
		"UNKNOWN":           0,
		"GPS":               1,
		"CONFIG":            2,
		"GEO_RESOLVER_TDOA": 3,
		"GEO_RESOLVER_RSSI": 4,
		"GEO_RESOLVER_GNSS": 5,
		"GEO_RESOLVER_WIFI": 6,
	}
)

func (x LocationSource) Enum() *LocationSource {
	p := new(LocationSource)
	*p = x
	return p
}

func (x LocationSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationSource) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[5].Descriptor()
}

func (LocationSource) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[5]
}

func (x LocationSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationSource.Descriptor instead.
func (LocationSource) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{5}
}

type Aggregation int32

const (
	// Hour.
	Aggregation_HOUR Aggregation = 0
	// Day.
	Aggregation_DAY Aggregation = 1
	// Month.
	Aggregation_MONTH Aggregation = 2
	// Minute.
	Aggregation_MINUTE Aggregation = 3
)

// Enum value maps for Aggregation.
var (
	Aggregation_name = map[int32]string{
		0: "HOUR",
		1: "DAY",
		2: "MONTH",
		3: "MINUTE",
	}
	Aggregation_value = map[string]int32{
		"HOUR":   0,
		"DAY":    1,
		"MONTH":  2,
		"MINUTE": 3,
	}
)

func (x Aggregation) Enum() *Aggregation {
	p := new(Aggregation)
	*p = x
	return p
}

func (x Aggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[6].Descriptor()
}

func (Aggregation) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[6]
}

func (x Aggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggregation.Descriptor instead.
func (Aggregation) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{6}
}

type MetricKind int32

const (
	// Incrementing counters that never decrease (these are not reset on each
	// reading).
	MetricKind_COUNTER MetricKind = 0
	// Counters that do get reset upon reading.
	MetricKind_ABSOLUTE MetricKind = 1
	// E.g. a temperature value.
	MetricKind_GAUGE MetricKind = 2
)

// Enum value maps for MetricKind.
var (
	MetricKind_name = map[int32]string{
		0: "COUNTER",
		1: "ABSOLUTE",
		2: "GAUGE",
	}
	MetricKind_value = map[string]int32{
		"COUNTER":  0,
		"ABSOLUTE": 1,
		"GAUGE":    2,
	}
)

func (x MetricKind) Enum() *MetricKind {
	p := new(MetricKind)
	*p = x
	return p
}

func (x MetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[7].Descriptor()
}

func (MetricKind) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[7]
}

func (x MetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricKind.Descriptor instead.
func (MetricKind) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{7}
}

type Regulation int32

const (
	// Unknown.
	Regulation_REGULATION_UNKNOWN Regulation = 0
	// ETSI EN 300 220.
	Regulation_ETSI_EN_300_220 Regulation = 1
)

// Enum value maps for Regulation.
var (
	Regulation_name = map[int32]string{
		0: "REGULATION_UNKNOWN",
		1: "ETSI_EN_300_220",
	}
	Regulation_value = map[string]int32{
		"REGULATION_UNKNOWN": 0,
		"ETSI_EN_300_220":    1,
	}
)

func (x Regulation) Enum() *Regulation {
	p := new(Regulation)
	*p = x
	return p
}

func (x Regulation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Regulation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[8].Descriptor()
}

func (Regulation) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[8]
}

func (x Regulation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Regulation.Descriptor instead.
func (Regulation) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{8}
}

type DeviceClass int32

const (
	// Class-A.
	DeviceClass_CLASS_A DeviceClass = 0
	// Class-B.
	DeviceClass_CLASS_B DeviceClass = 1
	// Class-C.
	DeviceClass_CLASS_C DeviceClass = 2
)

// Enum value maps for DeviceClass.
var (
	DeviceClass_name = map[int32]string{
		0: "CLASS_A",
		1: "CLASS_B",
		2: "CLASS_C",
	}
	DeviceClass_value = map[string]int32{
		"CLASS_A": 0,
		"CLASS_B": 1,
		"CLASS_C": 2,
	}
)

func (x DeviceClass) Enum() *DeviceClass {
	p := new(DeviceClass)
	*p = x
	return p
}

func (x DeviceClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceClass) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[9].Descriptor()
}

func (DeviceClass) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[9]
}

func (x DeviceClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceClass.Descriptor instead.
func (DeviceClass) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{9}
}

type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude.
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude.
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Altitude.
	Altitude float64 `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	// Location source.
	Source LocationSource `protobuf:"varint,4,opt,name=source,proto3,enum=common.LocationSource" json:"source,omitempty"`
	// Accuracy.
	Accuracy      float32 `protobuf:"fixed32,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Location) GetSource() LocationSource {
	if x != nil {
		return x.Source
	}
	return LocationSource_UNKNOWN
}

func (x *Location) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type KeyEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// KEK label.
	KekLabel string `protobuf:"bytes,1,opt,name=kek_label,json=kekLabel,proto3" json:"kek_label,omitempty"`
	// AES key (when the kek_label is set, this value must first be decrypted).
	AesKey        []byte `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEnvelope) Reset() {
	*x = KeyEnvelope{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEnvelope) ProtoMessage() {}

func (x *KeyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEnvelope.ProtoReflect.Descriptor instead.
func (*KeyEnvelope) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *KeyEnvelope) GetKekLabel() string {
	if x != nil {
		return x.KekLabel
	}
	return ""
}

func (x *KeyEnvelope) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Timestamps.
	Timestamps []*timestamppb.Timestamp `protobuf:"bytes,2,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	// Datasets.
	Datasets []*MetricDataset `protobuf:"bytes,3,rep,name=datasets,proto3" json:"datasets,omitempty"`
	// Kind.
	Kind          MetricKind `protobuf:"varint,4,opt,name=kind,proto3,enum=common.MetricKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetTimestamps() []*timestamppb.Timestamp {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *Metric) GetDatasets() []*MetricDataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *Metric) GetKind() MetricKind {
	if x != nil {
		return x.Kind
	}
	return MetricKind_COUNTER
}

type MetricDataset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Label.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Data.
	// Each value index corresponds with the same timestamp index of the Metric.
	Data          []float32 `protobuf:"fixed32,2,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDataset) Reset() {
	*x = MetricDataset{}
	mi := &file_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDataset) ProtoMessage() {}

func (x *MetricDataset) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDataset.ProtoReflect.Descriptor instead.
func (*MetricDataset) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *MetricDataset) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MetricDataset) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

// Join-Server context.
type JoinServerContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session-key ID.
	SessionKeyId string `protobuf:"bytes,1,opt,name=session_key_id,json=sessionKeyId,proto3" json:"session_key_id,omitempty"`
	// AppSKey envelope.
	AppSKey       *KeyEnvelope `protobuf:"bytes,2,opt,name=app_s_key,json=appSKey,proto3" json:"app_s_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinServerContext) Reset() {
	*x = JoinServerContext{}
	mi := &file_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinServerContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinServerContext) ProtoMessage() {}

func (x *JoinServerContext) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinServerContext.ProtoReflect.Descriptor instead.
func (*JoinServerContext) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *JoinServerContext) GetSessionKeyId() string {
	if x != nil {
		return x.SessionKeyId
	}
	return ""
}

func (x *JoinServerContext) GetAppSKey() *KeyEnvelope {
	if x != nil {
		return x.AppSKey
	}
	return nil
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\x12.\n" +
	"\x06source\x18\x04 \x01(\x0e2\x16.common.LocationSourceR\x06source\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\x02R\baccuracy\"C\n" +
	"\vKeyEnvelope\x12\x1b\n" +
	"\tkek_label\x18\x01 \x01(\tR\bkekLabel\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\fR\x06aesKey\"\xb3\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\n" +
	"timestamps\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampR\n" +
	"timestamps\x121\n" +
	"\bdatasets\x18\x03 \x03(\v2\x15.common.MetricDatasetR\bdatasets\x12&\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x12.common.MetricKindR\x04kind\"9\n" +
	"\rMetricDataset\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04data\x18\x02 \x03(\x02R\x04data\"j\n" +
	"\x11JoinServerContext\x12$\n" +
	"\x0esession_key_id\x18\x01 \x01(\tR\fsessionKeyId\x12/\n" +
	"\tapp_s_key\x18\x02 \x01(\v2\x13.common.KeyEnvelopeR\aappSKey*,\n" +
	"\n" +
	"Modulation\x12\b\n" +
	"\x04LORA\x10\x00\x12\a\n" +
	"\x03FSK\x10\x01\x12\v\n" +
	"\aLR_FHSS\x10\x02*\xaa\x01\n" +
	"\x06Region\x12\t\n" +
	"\x05EU868\x10\x00\x12\t\n" +
	"\x05US915\x10\x02\x12\t\n" +
	"\x05CN779\x10\x03\x12\t\n" +
	"\x05EU433\x10\x04\x12\t\n" +
	"\x05AU915\x10\x05\x12\t\n" +
	"\x05CN470\x10\x06\x12\t\n" +
	"\x05AS923\x10\a\x12\v\n" +
	"\aAS923_2\x10\f\x12\v\n" +
	"\aAS923_3\x10\r\x12\v\n" +
	"\aAS923_4\x10\x0e\x12\t\n" +
	"\x05KR920\x10\b\x12\t\n" +
	"\x05IN865\x10\t\x12\t\n" +
	"\x05RU864\x10\n" +
	"\x12\v\n" +
	"\aISM2400\x10\v*\xb3\x01\n" +
	"\x05FType\x12\x10\n" +
	"\fJOIN_REQUEST\x10\x00\x12\x0f\n" +
	"\vJOIN_ACCEPT\x10\x01\x12\x17\n" +
	"\x13UNCONFIRMED_DATA_UP\x10\x02\x12\x19\n" +
	"\x15UNCONFIRMED_DATA_DOWN\x10\x03\x12\x15\n" +
	"\x11CONFIRMED_DATA_UP\x10\x04\x12\x17\n" +
	"\x13CONFIRMED_DATA_DOWN\x10\x05\x12\x12\n" +
	"\x0eREJOIN_REQUEST\x10\x06\x12\x0f\n" +
	"\vPROPRIETARY\x10\a*~\n" +
	"\n" +
	"MacVersion\x12\x11\n" +
	"\rLORAWAN_1_0_0\x10\x00\x12\x11\n" +
	"\rLORAWAN_1_0_1\x10\x01\x12\x11\n" +
	"\rLORAWAN_1_0_2\x10\x02\x12\x11\n" +
	"\rLORAWAN_1_0_3\x10\x03\x12\x11\n" +
	"\rLORAWAN_1_0_4\x10\x04\x12\x11\n" +
	"\rLORAWAN_1_1_0\x10\x05*v\n" +
	"\x11RegParamsRevision\x12\x05\n" +
	"\x01A\x10\x00\x12\x05\n" +
	"\x01B\x10\x01\x12\x0f\n" +
	"\vRP002_1_0_0\x10\x02\x12\x0f\n" +
	"\vRP002_1_0_1\x10\x03\x12\x0f\n" +
	"\vRP002_1_0_2\x10\x04\x12\x0f\n" +
	"\vRP002_1_0_3\x10\x05\x12\x0f\n" +
	"\vRP002_1_0_4\x10\x06*\x8e\x01\n" +
	"\x0eLocationSource\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03GPS\x10\x01\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x02\x12\x15\n" +
	"\x11GEO_RESOLVER_TDOA\x10\x03\x12\x15\n" +
	"\x11GEO_RESOLVER_RSSI\x10\x04\x12\x15\n" +
	"\x11GEO_RESOLVER_GNSS\x10\x05\x12\x15\n" +
	"\x11GEO_RESOLVER_WIFI\x10\x06*7\n" +
	"\vAggregation\x12\b\n" +
	"\x04HOUR\x10\x00\x12\a\n" +
	"\x03DAY\x10\x01\x12\t\n" +
	"\x05MONTH\x10\x02\x12\n" +
	"\n" +
	"\x06MINUTE\x10\x03*2\n" +
	"\n" +
	"MetricKind\x12\v\n" +
	"\aCOUNTER\x10\x00\x12\f\n" +
	"\bABSOLUTE\x10\x01\x12\t\n" +
	"\x05GAUGE\x10\x02*9\n" +
	"\n" +
	"Regulation\x12\x16\n" +
	"\x12REGULATION_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fETSI_EN_300_220\x10\x01*4\n" +
	"\vDeviceClass\x12\v\n" +
	"\aCLASS_A\x10\x00\x12\v\n" +
	"\aCLASS_B\x10\x01\x12\v\n" +
	"\aCLASS_C\x10\x02B\x9d\x01\n" +
	"\x11io.chirpstack.apiB\vCommonProtoP\x01Z1github.com/chirpstack/chirpstack/api/go/v4/common\xaa\x02\x11Chirpstack.Common\xca\x02\x11Chirpstack\\Common\xe2\x02\x1dGPBMetadata\\Chirpstack\\Commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_common_proto_goTypes = []any{
	(Modulation)(0),               // 0: common.Modulation
	(Region)(0),                   // 1: common.Region
	(FType)(0),                    // 2: common.FType
	(MacVersion)(0),               // 3: common.MacVersion
	(RegParamsRevision)(0),        // 4: common.RegParamsRevision
	(LocationSource)(0),           // 5: common.LocationSource
	(Aggregation)(0),              // 6: common.Aggregation
	(MetricKind)(0),               // 7: common.MetricKind
	(Regulation)(0),               // 8: common.Regulation
	(DeviceClass)(0),              // 9: common.DeviceClass
	(*Location)(nil),              // 10: common.Location
	(*KeyEnvelope)(nil),           // 11: common.KeyEnvelope
	(*Metric)(nil),                // 12: common.Metric
	(*MetricDataset)(nil),         // 13: common.MetricDataset
	(*JoinServerContext)(nil),     // 14: common.JoinServerContext
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_common_common_proto_depIdxs = []int32{
	5,  // 0: common.Location.source:type_name -> common.LocationSource
	15, // 1: common.Metric.timestamps:type_name -> google.protobuf.Timestamp
	13, // 2: common.Metric.datasets:type_name -> common.MetricDataset
	7,  // 3: common.Metric.kind:type_name -> common.MetricKind
	11, // 4: common.JoinServerContext.app_s_key:type_name -> common.KeyEnvelope
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
