FROM rust:1.59.0-buster

ENV PROJECT_PATH=/chirpstack

RUN apt-get update && \
        apt-get install -y \
		make \
		cmake \
		git \
		bash \
		screen \
		postgresql-client \
		mosquitto-clients \
		redis-tools \
		rpm \
		clang \
		gcc-arm-linux-gnueabi \
		g++-arm-linux-gnueabi \
		gcc-arm-linux-gnueabihf \
		g++-arm-linux-gnueabihf \
		gcc-aarch64-linux-gnu \
		g++-aarch64-linux-gnu \
		&& apt-get clean

RUN rustup component add rustfmt clippy
RUN cargo install diesel_cli --no-default-features --features postgres
RUN cargo install cargo-deb
RUN cargo install cargo-rpm

RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH/chirpstack
