{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chirpstack.fullname" . }}-redis
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "chirpstack.redis.host" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "chirpstack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "chirpstack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
            - --save
            - "60"
            - "1"
            - --loglevel
            - warning
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 3
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.storage.storageClass }}
        storageClassName: {{ .Values.redis.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storage.size }}
{{- end }}
