/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.exportSymbol('google.api.api_visibility', null, global);
goog.exportSymbol('google.api.enum_visibility', null, global);
goog.exportSymbol('google.api.field_visibility', null, global);
goog.exportSymbol('google.api.message_visibility', null, global);
goog.exportSymbol('google.api.method_visibility', null, global);
goog.exportSymbol('google.api.value_visibility', null, global);
goog.exportSymbol('proto.google.api.Visibility', null, global);
goog.exportSymbol('proto.google.api.VisibilityRule', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.Visibility = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.Visibility.repeatedFields_, null);
};
goog.inherits(proto.google.api.Visibility, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.Visibility.displayName = 'proto.google.api.Visibility';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.Visibility.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.Visibility.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.Visibility.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.Visibility} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.Visibility.toObject = function(includeInstance, msg) {
  var f, obj = {
    rulesList: jspb.Message.toObjectList(msg.getRulesList(),
    proto.google.api.VisibilityRule.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.Visibility}
 */
proto.google.api.Visibility.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.Visibility;
  return proto.google.api.Visibility.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.Visibility} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.Visibility}
 */
proto.google.api.Visibility.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.api.VisibilityRule;
      reader.readMessage(value,proto.google.api.VisibilityRule.deserializeBinaryFromReader);
      msg.getRulesList().push(value);
      msg.setRulesList(msg.getRulesList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.google.api.Visibility} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.Visibility.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.Visibility.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.Visibility.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getRulesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.api.VisibilityRule.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.google.api.Visibility} The clone.
 */
proto.google.api.Visibility.prototype.cloneMessage = function() {
  return /** @type {!proto.google.api.Visibility} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated VisibilityRule rules = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.api.VisibilityRule>}
 */
proto.google.api.Visibility.prototype.getRulesList = function() {
  return /** @type{!Array.<!proto.google.api.VisibilityRule>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.api.VisibilityRule, 1));
};


/** @param {Array.<!proto.google.api.VisibilityRule>} value  */
proto.google.api.Visibility.prototype.setRulesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.google.api.Visibility.prototype.clearRulesList = function() {
  this.setRulesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.VisibilityRule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.VisibilityRule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.VisibilityRule.displayName = 'proto.google.api.VisibilityRule';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.VisibilityRule.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.VisibilityRule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.VisibilityRule} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.VisibilityRule.toObject = function(includeInstance, msg) {
  var f, obj = {
    selector: msg.getSelector(),
    restriction: msg.getRestriction()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.VisibilityRule}
 */
proto.google.api.VisibilityRule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.VisibilityRule;
  return proto.google.api.VisibilityRule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.VisibilityRule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.VisibilityRule}
 */
proto.google.api.VisibilityRule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSelector(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRestriction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.google.api.VisibilityRule} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.VisibilityRule.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.VisibilityRule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.VisibilityRule.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getSelector();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getRestriction();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.google.api.VisibilityRule} The clone.
 */
proto.google.api.VisibilityRule.prototype.cloneMessage = function() {
  return /** @type {!proto.google.api.VisibilityRule} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string selector = 1;
 * @return {string}
 */
proto.google.api.VisibilityRule.prototype.getSelector = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.google.api.VisibilityRule.prototype.setSelector = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string restriction = 2;
 * @return {string}
 */
proto.google.api.VisibilityRule.prototype.getRestriction = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.google.api.VisibilityRule.prototype.setRestriction = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `enumVisibility`.
 * @type {!jspb.ExtensionFieldInfo.<!proto.google.api.VisibilityRule>}
 */
proto.google.api.enumVisibility = new jspb.ExtensionFieldInfo(
    72295727,
    {enumVisibility: 0},
    proto.google.api.VisibilityRule,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.google.api.VisibilityRule.toObject),
    0);

google_protobuf_descriptor_pb.EnumOptions.extensionsBinary[72295727] = new jspb.ExtensionFieldBinaryInfo(
    proto.google.api.enumVisibility,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.google.api.VisibilityRule.serializeBinaryToWriter,
    proto.google.api.VisibilityRule.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.EnumOptions.extensions[72295727] = proto.google.api.enumVisibility;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `valueVisibility`.
 * @type {!jspb.ExtensionFieldInfo.<!proto.google.api.VisibilityRule>}
 */
proto.google.api.valueVisibility = new jspb.ExtensionFieldInfo(
    72295727,
    {valueVisibility: 0},
    proto.google.api.VisibilityRule,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.google.api.VisibilityRule.toObject),
    0);

google_protobuf_descriptor_pb.EnumValueOptions.extensionsBinary[72295727] = new jspb.ExtensionFieldBinaryInfo(
    proto.google.api.valueVisibility,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.google.api.VisibilityRule.serializeBinaryToWriter,
    proto.google.api.VisibilityRule.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.EnumValueOptions.extensions[72295727] = proto.google.api.valueVisibility;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `fieldVisibility`.
 * @type {!jspb.ExtensionFieldInfo.<!proto.google.api.VisibilityRule>}
 */
proto.google.api.fieldVisibility = new jspb.ExtensionFieldInfo(
    72295727,
    {fieldVisibility: 0},
    proto.google.api.VisibilityRule,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.google.api.VisibilityRule.toObject),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[72295727] = new jspb.ExtensionFieldBinaryInfo(
    proto.google.api.fieldVisibility,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.google.api.VisibilityRule.serializeBinaryToWriter,
    proto.google.api.VisibilityRule.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[72295727] = proto.google.api.fieldVisibility;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `messageVisibility`.
 * @type {!jspb.ExtensionFieldInfo.<!proto.google.api.VisibilityRule>}
 */
proto.google.api.messageVisibility = new jspb.ExtensionFieldInfo(
    72295727,
    {messageVisibility: 0},
    proto.google.api.VisibilityRule,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.google.api.VisibilityRule.toObject),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[72295727] = new jspb.ExtensionFieldBinaryInfo(
    proto.google.api.messageVisibility,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.google.api.VisibilityRule.serializeBinaryToWriter,
    proto.google.api.VisibilityRule.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[72295727] = proto.google.api.messageVisibility;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `methodVisibility`.
 * @type {!jspb.ExtensionFieldInfo.<!proto.google.api.VisibilityRule>}
 */
proto.google.api.methodVisibility = new jspb.ExtensionFieldInfo(
    72295727,
    {methodVisibility: 0},
    proto.google.api.VisibilityRule,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.google.api.VisibilityRule.toObject),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[72295727] = new jspb.ExtensionFieldBinaryInfo(
    proto.google.api.methodVisibility,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.google.api.VisibilityRule.serializeBinaryToWriter,
    proto.google.api.VisibilityRule.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[72295727] = proto.google.api.methodVisibility;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `apiVisibility`.
 * @type {!jspb.ExtensionFieldInfo.<!proto.google.api.VisibilityRule>}
 */
proto.google.api.apiVisibility = new jspb.ExtensionFieldInfo(
    72295727,
    {apiVisibility: 0},
    proto.google.api.VisibilityRule,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.google.api.VisibilityRule.toObject),
    0);

google_protobuf_descriptor_pb.ServiceOptions.extensionsBinary[72295727] = new jspb.ExtensionFieldBinaryInfo(
    proto.google.api.apiVisibility,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.google.api.VisibilityRule.serializeBinaryToWriter,
    proto.google.api.VisibilityRule.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.ServiceOptions.extensions[72295727] = proto.google.api.apiVisibility;

goog.object.extend(exports, proto.google.api);
