"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Encoding(_Encoding, metaclass=_EncodingEnumTypeWrapper):
    pass
class _Encoding:
    V = typing.NewType('V', builtins.int)
class _EncodingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Encoding.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    JSON = Encoding.V(0)
    PROTOBUF = Encoding.V(1)

JSON = Encoding.V(0)
PROTOBUF = Encoding.V(1)
global___Encoding = Encoding


class IntegrationKind(_IntegrationKind, metaclass=_IntegrationKindEnumTypeWrapper):
    pass
class _IntegrationKind:
    V = typing.NewType('V', builtins.int)
class _IntegrationKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IntegrationKind.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    HTTP = IntegrationKind.V(0)
    INFLUX_DB = IntegrationKind.V(1)
    THINGS_BOARD = IntegrationKind.V(2)
    MY_DEVICES = IntegrationKind.V(3)
    LORA_CLOUD = IntegrationKind.V(4)
    GCP_PUB_SUB = IntegrationKind.V(5)
    AWS_SNS = IntegrationKind.V(6)
    AZURE_SERVICE_BUS = IntegrationKind.V(7)
    PILOT_THINGS = IntegrationKind.V(8)
    MQTT_GLOBAL = IntegrationKind.V(9)
    IFTTT = IntegrationKind.V(10)

HTTP = IntegrationKind.V(0)
INFLUX_DB = IntegrationKind.V(1)
THINGS_BOARD = IntegrationKind.V(2)
MY_DEVICES = IntegrationKind.V(3)
LORA_CLOUD = IntegrationKind.V(4)
GCP_PUB_SUB = IntegrationKind.V(5)
AWS_SNS = IntegrationKind.V(6)
AZURE_SERVICE_BUS = IntegrationKind.V(7)
PILOT_THINGS = IntegrationKind.V(8)
MQTT_GLOBAL = IntegrationKind.V(9)
IFTTT = IntegrationKind.V(10)
global___IntegrationKind = IntegrationKind


class InfluxDbPrecision(_InfluxDbPrecision, metaclass=_InfluxDbPrecisionEnumTypeWrapper):
    pass
class _InfluxDbPrecision:
    V = typing.NewType('V', builtins.int)
class _InfluxDbPrecisionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InfluxDbPrecision.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NS = InfluxDbPrecision.V(0)
    U = InfluxDbPrecision.V(1)
    MS = InfluxDbPrecision.V(2)
    S = InfluxDbPrecision.V(3)
    M = InfluxDbPrecision.V(4)
    H = InfluxDbPrecision.V(5)

NS = InfluxDbPrecision.V(0)
U = InfluxDbPrecision.V(1)
MS = InfluxDbPrecision.V(2)
S = InfluxDbPrecision.V(3)
M = InfluxDbPrecision.V(4)
H = InfluxDbPrecision.V(5)
global___InfluxDbPrecision = InfluxDbPrecision


class InfluxDbVersion(_InfluxDbVersion, metaclass=_InfluxDbVersionEnumTypeWrapper):
    pass
class _InfluxDbVersion:
    V = typing.NewType('V', builtins.int)
class _InfluxDbVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InfluxDbVersion.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    INFLUXDB_1 = InfluxDbVersion.V(0)
    INFLUXDB_2 = InfluxDbVersion.V(1)

INFLUXDB_1 = InfluxDbVersion.V(0)
INFLUXDB_2 = InfluxDbVersion.V(1)
global___InfluxDbVersion = InfluxDbVersion


class Application(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TENANT_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    # Note: on create this will be automatically generated.
    id: typing.Text = ...
    # Application name.
    name: typing.Text = ...
    # Application description.
    description: typing.Text = ...
    # Tenant ID (UUID).
    tenant_id: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        name : typing.Text = ...,
        description : typing.Text = ...,
        tenant_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"description",b"description",u"id",b"id",u"name",b"name",u"tenant_id",b"tenant_id"]) -> None: ...
global___Application = Application

class ApplicationListItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    id: typing.Text = ...
    # Created at timestamp.
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    # Last update timestamp.
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    # Application name.
    name: typing.Text = ...
    # Application description.
    description: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        created_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        name : typing.Text = ...,
        description : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"created_at",b"created_at",u"updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"created_at",b"created_at",u"description",b"description",u"id",b"id",u"name",b"name",u"updated_at",b"updated_at"]) -> None: ...
global___ApplicationListItem = ApplicationListItem

class CreateApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_FIELD_NUMBER: builtins.int
    # Application object to create.
    @property
    def application(self) -> global___Application: ...
    def __init__(self,
        *,
        application : typing.Optional[global___Application] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"application",b"application"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application",b"application"]) -> None: ...
global___CreateApplicationRequest = CreateApplicationRequest

class CreateApplicationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    id: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id"]) -> None: ...
global___CreateApplicationResponse = CreateApplicationResponse

class GetApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    id: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id"]) -> None: ...
global___GetApplicationRequest = GetApplicationRequest

class GetApplicationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    MEASUREMENT_KEYS_FIELD_NUMBER: builtins.int
    # Application object.
    @property
    def application(self) -> global___Application: ...
    # Created at timestamp.
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    # Last update timestamp.
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    # Measurement keys.
    # This contains the measurement keys from all the device-profiles that
    # are used by the devices under this application.
    @property
    def measurement_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        application : typing.Optional[global___Application] = ...,
        created_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        measurement_keys : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"application",b"application",u"created_at",b"created_at",u"updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application",b"application",u"created_at",b"created_at",u"measurement_keys",b"measurement_keys",u"updated_at",b"updated_at"]) -> None: ...
global___GetApplicationResponse = GetApplicationResponse

class UpdateApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_FIELD_NUMBER: builtins.int
    # Application object.
    @property
    def application(self) -> global___Application: ...
    def __init__(self,
        *,
        application : typing.Optional[global___Application] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"application",b"application"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application",b"application"]) -> None: ...
global___UpdateApplicationRequest = UpdateApplicationRequest

class DeleteApplicationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    id: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id"]) -> None: ...
global___DeleteApplicationRequest = DeleteApplicationRequest

class ListApplicationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LIMIT_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    SEARCH_FIELD_NUMBER: builtins.int
    TENANT_ID_FIELD_NUMBER: builtins.int
    # Max number of applications to return in the result-set.
    limit: builtins.int = ...
    # Offset in the result-set (for pagination).
    offset: builtins.int = ...
    # If set, the given string will be used to search on name (optional).
    search: typing.Text = ...
    # Tenant ID to list the applications for.
    tenant_id: typing.Text = ...
    def __init__(self,
        *,
        limit : builtins.int = ...,
        offset : builtins.int = ...,
        search : typing.Text = ...,
        tenant_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"limit",b"limit",u"offset",b"offset",u"search",b"search",u"tenant_id",b"tenant_id"]) -> None: ...
global___ListApplicationsRequest = ListApplicationsRequest

class ListApplicationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TOTAL_COUNT_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    # Total number of applications.
    total_count: builtins.int = ...
    # Result-set.
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ApplicationListItem]: ...
    def __init__(self,
        *,
        total_count : builtins.int = ...,
        result : typing.Optional[typing.Iterable[global___ApplicationListItem]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"result",b"result",u"total_count",b"total_count"]) -> None: ...
global___ListApplicationsResponse = ListApplicationsResponse

class ListIntegrationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___ListIntegrationsRequest = ListIntegrationsRequest

class IntegrationListItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KIND_FIELD_NUMBER: builtins.int
    # Integration kind.
    kind: global___IntegrationKind.V = ...
    def __init__(self,
        *,
        kind : global___IntegrationKind.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"kind",b"kind"]) -> None: ...
global___IntegrationListItem = IntegrationListItem

class ListIntegrationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TOTAL_COUNT_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    # Total number of integrations available within the result-set.
    total_count: builtins.int = ...
    # Integrations within result-set.
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IntegrationListItem]: ...
    def __init__(self,
        *,
        total_count : builtins.int = ...,
        result : typing.Optional[typing.Iterable[global___IntegrationListItem]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"result",b"result",u"total_count",b"total_count"]) -> None: ...
global___ListIntegrationsResponse = ListIntegrationsResponse

class HttpIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    EVENT_ENDPOINT_URL_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    # HTTP headers to set when making requests.
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Payload encoding.
    encoding: global___Encoding.V = ...
    # Event endpoint URL.
    # The HTTP integration will POST all events to this enpoint. The request
    # will contain a query parameters "event" containing the type of the
    # event.
    event_endpoint_url: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        headers : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        encoding : global___Encoding.V = ...,
        event_endpoint_url : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"encoding",b"encoding",u"event_endpoint_url",b"event_endpoint_url",u"headers",b"headers"]) -> None: ...
global___HttpIntegration = HttpIntegration

class CreateHttpIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___HttpIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___HttpIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateHttpIntegrationRequest = CreateHttpIntegrationRequest

class GetHttpIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetHttpIntegrationRequest = GetHttpIntegrationRequest

class GetHttpIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___HttpIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___HttpIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetHttpIntegrationResponse = GetHttpIntegrationResponse

class UpdateHttpIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___HttpIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___HttpIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateHttpIntegrationRequest = UpdateHttpIntegrationRequest

class DeleteHttpIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteHttpIntegrationRequest = DeleteHttpIntegrationRequest

class InfluxDbIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    DB_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    RETENTION_POLICY_NAME_FIELD_NUMBER: builtins.int
    PRECISION_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    ORGANIZATION_FIELD_NUMBER: builtins.int
    BUCKET_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    # InfluxDb API write endpoint (e.g. http://localhost:8086/write).
    endpoint: typing.Text = ...
    # InfluxDb database name. (InfluxDb v1)
    db: typing.Text = ...
    # InfluxDb username. (InfluxDb v1)
    username: typing.Text = ...
    # InfluxDb password. (InfluxDb v1)
    password: typing.Text = ...
    # InfluxDb retention policy name. (InfluxDb v1)
    retention_policy_name: typing.Text = ...
    # InfluxDb timestamp precision (InfluxDb v1).
    precision: global___InfluxDbPrecision.V = ...
    # InfluxDb version.
    version: global___InfluxDbVersion.V = ...
    # Token. (InfluxDb v2)
    token: typing.Text = ...
    # Organization. (InfluxDb v2)
    organization: typing.Text = ...
    # Bucket. (InfluxDb v2)
    bucket: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        endpoint : typing.Text = ...,
        db : typing.Text = ...,
        username : typing.Text = ...,
        password : typing.Text = ...,
        retention_policy_name : typing.Text = ...,
        precision : global___InfluxDbPrecision.V = ...,
        version : global___InfluxDbVersion.V = ...,
        token : typing.Text = ...,
        organization : typing.Text = ...,
        bucket : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"bucket",b"bucket",u"db",b"db",u"endpoint",b"endpoint",u"organization",b"organization",u"password",b"password",u"precision",b"precision",u"retention_policy_name",b"retention_policy_name",u"token",b"token",u"username",b"username",u"version",b"version"]) -> None: ...
global___InfluxDbIntegration = InfluxDbIntegration

class CreateInfluxDbIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___InfluxDbIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___InfluxDbIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateInfluxDbIntegrationRequest = CreateInfluxDbIntegrationRequest

class GetInfluxDbIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetInfluxDbIntegrationRequest = GetInfluxDbIntegrationRequest

class GetInfluxDbIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___InfluxDbIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___InfluxDbIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetInfluxDbIntegrationResponse = GetInfluxDbIntegrationResponse

class UpdateInfluxDbIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___InfluxDbIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___InfluxDbIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateInfluxDbIntegrationRequest = UpdateInfluxDbIntegrationRequest

class DeleteInfluxDbIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteInfluxDbIntegrationRequest = DeleteInfluxDbIntegrationRequest

class ThingsBoardIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    SERVER_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    # ThingsBoard server endpoint, e.g. https://example.com
    server: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        server : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"server",b"server"]) -> None: ...
global___ThingsBoardIntegration = ThingsBoardIntegration

class CreateThingsBoardIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___ThingsBoardIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___ThingsBoardIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateThingsBoardIntegrationRequest = CreateThingsBoardIntegrationRequest

class GetThingsBoardIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetThingsBoardIntegrationRequest = GetThingsBoardIntegrationRequest

class GetThingsBoardIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___ThingsBoardIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___ThingsBoardIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetThingsBoardIntegrationResponse = GetThingsBoardIntegrationResponse

class UpdateThingsBoardIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___ThingsBoardIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___ThingsBoardIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateThingsBoardIntegrationRequest = UpdateThingsBoardIntegrationRequest

class DeleteThingsBoardIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteThingsBoardIntegrationRequest = DeleteThingsBoardIntegrationRequest

class MyDevicesIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    # myDevices API endpoint.
    endpoint: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        endpoint : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"endpoint",b"endpoint"]) -> None: ...
global___MyDevicesIntegration = MyDevicesIntegration

class CreateMyDevicesIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___MyDevicesIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___MyDevicesIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateMyDevicesIntegrationRequest = CreateMyDevicesIntegrationRequest

class GetMyDevicesIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetMyDevicesIntegrationRequest = GetMyDevicesIntegrationRequest

class GetMyDevicesIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___MyDevicesIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___MyDevicesIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetMyDevicesIntegrationResponse = GetMyDevicesIntegrationResponse

class UpdateMyDevicesIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___MyDevicesIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___MyDevicesIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateMyDevicesIntegrationRequest = UpdateMyDevicesIntegrationRequest

class DeleteMyDevicesIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUIO).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteMyDevicesIntegrationRequest = DeleteMyDevicesIntegrationRequest

class LoraCloudIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    MODEM_GEOLOCATION_SERVICES_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    # Modem & Geolocation Services configuration.
    @property
    def modem_geolocation_services(self) -> global___LoraCloudModemGeolocationServices: ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        modem_geolocation_services : typing.Optional[global___LoraCloudModemGeolocationServices] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"modem_geolocation_services",b"modem_geolocation_services"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"modem_geolocation_services",b"modem_geolocation_services"]) -> None: ...
global___LoraCloudIntegration = LoraCloudIntegration

class LoraCloudModemGeolocationServices(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TOKEN_FIELD_NUMBER: builtins.int
    MODEM_ENABLED_FIELD_NUMBER: builtins.int
    MODEM_PORT_FIELD_NUMBER: builtins.int
    GNSS_PORT_FIELD_NUMBER: builtins.int
    GNSS_USE_RX_TIME_FIELD_NUMBER: builtins.int
    PARSE_TLV_FIELD_NUMBER: builtins.int
    GEOLOCATION_BUFFER_TTL_FIELD_NUMBER: builtins.int
    GEOLOCATION_MIN_BUFFER_SIZE_FIELD_NUMBER: builtins.int
    GEOLOCATION_TDOA_FIELD_NUMBER: builtins.int
    GEOLOCATION_RSSI_FIELD_NUMBER: builtins.int
    GEOLOCATION_GNSS_FIELD_NUMBER: builtins.int
    GEOLOCATION_GNSS_PAYLOAD_FIELD_FIELD_NUMBER: builtins.int
    GEOLOCATION_GNSS_USE_RX_TIME_FIELD_NUMBER: builtins.int
    GEOLOCATION_WIFI_FIELD_NUMBER: builtins.int
    GEOLOCATION_WIFI_PAYLOAD_FIELD_FIELD_NUMBER: builtins.int
    # API token.
    token: typing.Text = ...
    # Device implements Modem / Modem-E stack.
    modem_enabled: builtins.bool = ...
    # Modem port (fPort).
    # ChirpStack will only forward the FrmPayload to the MGS if the port
    # is equal to the configured value.
    modem_port: builtins.int = ...
    # GNSS port (fPort).
    # ChirpStack will forward the FrmPayload to MGS as GNSS payload if the
    # port is equal to the configured value.
    gnss_port: builtins.int = ...
    # Use rx time for GNSS resolving.
    # In case this is set to true, the MGS resolver will use the RX time of the
    # network instead of the timestamp included in the LR1110 payload.
    gnss_use_rx_time: builtins.bool = ...
    # Parse TLV records.
    # If enabled, stream records (expected in TLV format) are scanned for GNSS
    # data (0x06 or 0x07). If found, ChirpStack will make an additional
    # geolocation call to the MGS API for resolving the location of the detected
    # payload.
    parse_tlv: builtins.bool = ...
    # Geolocation buffer TTL (in seconds).
    # If > 0, uplink RX meta-data will be stored in a buffer so that
    # the meta-data of multiple uplinks can be used for geolocation.
    geolocation_buffer_ttl: builtins.int = ...
    # Geolocation minimum buffer size.
    # If > 0, geolocation will only be performed when the buffer has
    # at least the given size.
    geolocation_min_buffer_size: builtins.int = ...
    # TDOA based geolocation is enabled.
    geolocation_tdoa: builtins.bool = ...
    # RSSI based geolocation is enabled.
    geolocation_rssi: builtins.bool = ...
    # GNSS based geolocation is enabled (LR1110).
    geolocation_gnss: builtins.bool = ...
    # GNSS payload field.
    # This holds the name of the field in the decoded payload object which
    # contains the GNSS payload bytes (as HEX string).
    geolocation_gnss_payload_field: typing.Text = ...
    # GNSS use RX time.
    # In case this is set to true, the resolver will use the RX time of the
    # network instead of the timestamp included in the LR1110 payload.
    geolocation_gnss_use_rx_time: builtins.bool = ...
    # Wifi based geolocation is enabled.
    geolocation_wifi: builtins.bool = ...
    # Wifi payload field.
    # This holds the name of the field in the decoded payload object which
    # contains an array of objects with the following fields:
    # * macAddress - e.g. 01:23:45:67:89:ab
    # * signalStrength - e.g. -51 (optional)
    geolocation_wifi_payload_field: typing.Text = ...
    def __init__(self,
        *,
        token : typing.Text = ...,
        modem_enabled : builtins.bool = ...,
        modem_port : builtins.int = ...,
        gnss_port : builtins.int = ...,
        gnss_use_rx_time : builtins.bool = ...,
        parse_tlv : builtins.bool = ...,
        geolocation_buffer_ttl : builtins.int = ...,
        geolocation_min_buffer_size : builtins.int = ...,
        geolocation_tdoa : builtins.bool = ...,
        geolocation_rssi : builtins.bool = ...,
        geolocation_gnss : builtins.bool = ...,
        geolocation_gnss_payload_field : typing.Text = ...,
        geolocation_gnss_use_rx_time : builtins.bool = ...,
        geolocation_wifi : builtins.bool = ...,
        geolocation_wifi_payload_field : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"geolocation_buffer_ttl",b"geolocation_buffer_ttl",u"geolocation_gnss",b"geolocation_gnss",u"geolocation_gnss_payload_field",b"geolocation_gnss_payload_field",u"geolocation_gnss_use_rx_time",b"geolocation_gnss_use_rx_time",u"geolocation_min_buffer_size",b"geolocation_min_buffer_size",u"geolocation_rssi",b"geolocation_rssi",u"geolocation_tdoa",b"geolocation_tdoa",u"geolocation_wifi",b"geolocation_wifi",u"geolocation_wifi_payload_field",b"geolocation_wifi_payload_field",u"gnss_port",b"gnss_port",u"gnss_use_rx_time",b"gnss_use_rx_time",u"modem_enabled",b"modem_enabled",u"modem_port",b"modem_port",u"parse_tlv",b"parse_tlv",u"token",b"token"]) -> None: ...
global___LoraCloudModemGeolocationServices = LoraCloudModemGeolocationServices

class CreateLoraCloudIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___LoraCloudIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___LoraCloudIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateLoraCloudIntegrationRequest = CreateLoraCloudIntegrationRequest

class GetLoraCloudIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetLoraCloudIntegrationRequest = GetLoraCloudIntegrationRequest

class GetLoraCloudIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___LoraCloudIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___LoraCloudIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetLoraCloudIntegrationResponse = GetLoraCloudIntegrationResponse

class UpdateLoraCloudIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___LoraCloudIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___LoraCloudIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateLoraCloudIntegrationRequest = UpdateLoraCloudIntegrationRequest

class DeleteLoraCloudIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteLoraCloudIntegrationRequest = DeleteLoraCloudIntegrationRequest

class GcpPubSubIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    CREDENTIALS_FILE_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    TOPIC_NAME_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    # Encoding.
    encoding: global___Encoding.V = ...
    # Credentials file.
    # This IAM service-account credentials file (JSON) must have the following Pub/Sub roles:
    # * Pub/Sub Publisher
    credentials_file: typing.Text = ...
    # Project ID.
    project_id: typing.Text = ...
    # Topic name.
    # This is the name of the Pub/Sub topic.
    topic_name: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        encoding : global___Encoding.V = ...,
        credentials_file : typing.Text = ...,
        project_id : typing.Text = ...,
        topic_name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"credentials_file",b"credentials_file",u"encoding",b"encoding",u"project_id",b"project_id",u"topic_name",b"topic_name"]) -> None: ...
global___GcpPubSubIntegration = GcpPubSubIntegration

class CreateGcpPubSubIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___GcpPubSubIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___GcpPubSubIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateGcpPubSubIntegrationRequest = CreateGcpPubSubIntegrationRequest

class GetGcpPubSubIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetGcpPubSubIntegrationRequest = GetGcpPubSubIntegrationRequest

class GetGcpPubSubIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___GcpPubSubIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___GcpPubSubIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetGcpPubSubIntegrationResponse = GetGcpPubSubIntegrationResponse

class UpdateGcpPubSubIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___GcpPubSubIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___GcpPubSubIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateGcpPubSubIntegrationRequest = UpdateGcpPubSubIntegrationRequest

class DeleteGcpPubSubIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteGcpPubSubIntegrationRequest = DeleteGcpPubSubIntegrationRequest

class AwsSnsIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    REGION_FIELD_NUMBER: builtins.int
    ACCESS_KEY_ID_FIELD_NUMBER: builtins.int
    SECRET_ACCESS_KEY_FIELD_NUMBER: builtins.int
    TOPIC_ARN_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    # Encoding.
    encoding: global___Encoding.V = ...
    # AWS region.
    region: typing.Text = ...
    # AWS Access Key ID.
    access_key_id: typing.Text = ...
    # AWS Secret Access Key.
    secret_access_key: typing.Text = ...
    # Topic ARN.
    topic_arn: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        encoding : global___Encoding.V = ...,
        region : typing.Text = ...,
        access_key_id : typing.Text = ...,
        secret_access_key : typing.Text = ...,
        topic_arn : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"access_key_id",b"access_key_id",u"application_id",b"application_id",u"encoding",b"encoding",u"region",b"region",u"secret_access_key",b"secret_access_key",u"topic_arn",b"topic_arn"]) -> None: ...
global___AwsSnsIntegration = AwsSnsIntegration

class CreateAwsSnsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___AwsSnsIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___AwsSnsIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateAwsSnsIntegrationRequest = CreateAwsSnsIntegrationRequest

class GetAwsSnsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetAwsSnsIntegrationRequest = GetAwsSnsIntegrationRequest

class GetAwsSnsIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___AwsSnsIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___AwsSnsIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetAwsSnsIntegrationResponse = GetAwsSnsIntegrationResponse

class UpdateAwsSnsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___AwsSnsIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___AwsSnsIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateAwsSnsIntegrationRequest = UpdateAwsSnsIntegrationRequest

class DeleteAwsSnsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteAwsSnsIntegrationRequest = DeleteAwsSnsIntegrationRequest

class AzureServiceBusIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    CONNECTION_STRING_FIELD_NUMBER: builtins.int
    PUBLISH_NAME_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    # Encoding.
    encoding: global___Encoding.V = ...
    # Connection string.
    connection_string: typing.Text = ...
    # Publish name.
    # This is the name of the topic or queue.
    publish_name: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        encoding : global___Encoding.V = ...,
        connection_string : typing.Text = ...,
        publish_name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"connection_string",b"connection_string",u"encoding",b"encoding",u"publish_name",b"publish_name"]) -> None: ...
global___AzureServiceBusIntegration = AzureServiceBusIntegration

class CreateAzureServiceBusIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___AzureServiceBusIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___AzureServiceBusIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateAzureServiceBusIntegrationRequest = CreateAzureServiceBusIntegrationRequest

class GetAzureServiceBusIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetAzureServiceBusIntegrationRequest = GetAzureServiceBusIntegrationRequest

class GetAzureServiceBusIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___AzureServiceBusIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___AzureServiceBusIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetAzureServiceBusIntegrationResponse = GetAzureServiceBusIntegrationResponse

class UpdateAzureServiceBusIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___AzureServiceBusIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___AzureServiceBusIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateAzureServiceBusIntegrationRequest = UpdateAzureServiceBusIntegrationRequest

class DeleteAzureServiceBusIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteAzureServiceBusIntegrationRequest = DeleteAzureServiceBusIntegrationRequest

class PilotThingsIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    SERVER_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    # Server URL.
    server: typing.Text = ...
    # Authentication token.
    token: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        server : typing.Text = ...,
        token : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"server",b"server",u"token",b"token"]) -> None: ...
global___PilotThingsIntegration = PilotThingsIntegration

class CreatePilotThingsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to create.
    @property
    def integration(self) -> global___PilotThingsIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___PilotThingsIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreatePilotThingsIntegrationRequest = CreatePilotThingsIntegrationRequest

class GetPilotThingsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetPilotThingsIntegrationRequest = GetPilotThingsIntegrationRequest

class GetPilotThingsIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___PilotThingsIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___PilotThingsIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetPilotThingsIntegrationResponse = GetPilotThingsIntegrationResponse

class UpdatePilotThingsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___PilotThingsIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___PilotThingsIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdatePilotThingsIntegrationRequest = UpdatePilotThingsIntegrationRequest

class DeletePilotThingsIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeletePilotThingsIntegrationRequest = DeletePilotThingsIntegrationRequest

class IftttIntegration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    UPLINK_VALUES_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    # Key.
    # This key can be obtained from the IFTTT Webhooks documentation page.
    key: typing.Text = ...
    # Values.
    # Up to 2 values can be forwarded to IFTTT. These values must map to the
    # decoded payload keys. For example:
    # {
    #   "batteryLevel": 75.3,
    #   "buttons": [{"pressed": false}, {"pressed": true}]
    # }
    # You would specify the following fields:
    # uplink_values = ["batteryLevel", "buttons_0_pressed"]
    #
    # Note: The first value is always used for the DevEUI.
    @property
    def uplink_values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        key : typing.Text = ...,
        uplink_values : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"key",b"key",u"uplink_values",b"uplink_values"]) -> None: ...
global___IftttIntegration = IftttIntegration

class CreateIftttIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___IftttIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___IftttIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___CreateIftttIntegrationRequest = CreateIftttIntegrationRequest

class GetIftttIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GetIftttIntegrationRequest = GetIftttIntegrationRequest

class GetIftttIntegrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object.
    @property
    def integration(self) -> global___IftttIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___IftttIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___GetIftttIntegrationResponse = GetIftttIntegrationResponse

class UpdateIftttIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTEGRATION_FIELD_NUMBER: builtins.int
    # Integration object to update.
    @property
    def integration(self) -> global___IftttIntegration: ...
    def __init__(self,
        *,
        integration : typing.Optional[global___IftttIntegration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"integration",b"integration"]) -> None: ...
global___UpdateIftttIntegrationRequest = UpdateIftttIntegrationRequest

class DeleteIftttIntegrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___DeleteIftttIntegrationRequest = DeleteIftttIntegrationRequest

class GenerateMqttIntegrationClientCertificateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_ID_FIELD_NUMBER: builtins.int
    # Application ID (UUID).
    application_id: typing.Text = ...
    def __init__(self,
        *,
        application_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id"]) -> None: ...
global___GenerateMqttIntegrationClientCertificateRequest = GenerateMqttIntegrationClientCertificateRequest

class GenerateMqttIntegrationClientCertificateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TLS_CERT_FIELD_NUMBER: builtins.int
    TLS_KEY_FIELD_NUMBER: builtins.int
    CA_CERT_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    # TLS certificate.
    tls_cert: typing.Text = ...
    # TLS key.
    tls_key: typing.Text = ...
    # CA certificate.
    ca_cert: typing.Text = ...
    # Expires at defines the expiration date of the certificate.
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        tls_cert : typing.Text = ...,
        tls_key : typing.Text = ...,
        ca_cert : typing.Text = ...,
        expires_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"expires_at",b"expires_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ca_cert",b"ca_cert",u"expires_at",b"expires_at",u"tls_cert",b"tls_cert",u"tls_key",b"tls_key"]) -> None: ...
global___GenerateMqttIntegrationClientCertificateResponse = GenerateMqttIntegrationClientCertificateResponse
