apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chirpstack.fullname" . }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
data:
  chirpstack.toml: |
    [logging]
      level = {{ .Values.chirpstack.logging.level | quote }}

    [postgresql]
      dsn = "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@{{ include "chirpstack.postgresql.host" . }}:5432/$POSTGRES_DB?sslmode=disable"
      max_open_connections = 10
      min_idle_connections = 0
      connection_recycling_method = "verified"

    [redis]
      servers = ["redis://{{ include "chirpstack.redis.host" . }}:6379/"]
      cluster = false

    [api]
      bind = "0.0.0.0:8080"
      secret = "$CHIRPSTACK_API_SECRET"

    [integration]
      enabled = {{ .Values.chirpstack.integration.enabled | toJson }}

      [integration.mqtt]
        server = "{{ include "chirpstack.mosquitto.server" . }}/"
        json = {{ .Values.chirpstack.integration.mqtt.json }}

    [network]
      net_id = {{ .Values.chirpstack.network.netId | quote }}
      enabled_regions = {{ .Values.chirpstack.network.enabledRegions | toJson }}

    {{- if .Values.chirpstack.monitoring.enabled }}
    [monitoring]
      bind = {{ .Values.chirpstack.monitoring.bind | quote }}
    {{- end }}

  {{- $mosquittoServer := include "chirpstack.mosquitto.server" . }}
  {{- range $regionName, $regionContent := .Values.chirpstack.regions }}
  region_{{ $regionName }}.toml: |
    {{ include "chirpstack.regionContent" (dict "content" $regionContent "server" $mosquittoServer) | nindent 4 }}
  {{- end }}
