{{- if not .Values.chirpstack.apiSecretExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chirpstack.fullname" . }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  CHIRPSTACK_API_SECRET: {{ .Values.chirpstack.apiSecret | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
{{- end }}
