apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.fullname" . }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
  {{- with .Values.chirpstack.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.chirpstack.service.type }}
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chirpstack
  ports:
    - name: api
      port: {{ .Values.chirpstack.service.port }}
      targetPort: api
      protocol: TCP
    {{- if .Values.chirpstack.monitoring.enabled }}
    - name: monitoring
      port: {{ .Values.chirpstack.service.monitoringPort }}
      targetPort: monitoring
      protocol: TCP
    {{- end }}
