apiVersion: v1
kind: Service
metadata:
  name: chirpstack
  namespace: chirpstack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chirpstack
    app.kubernetes.io/instance: chirpstack
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: monitoring
      port: 8081
      targetPort: 8081
