// GENERATED CODE -- DO NOT EDIT!

// package: api
// file: api/application.proto

import * as api_application_pb from "../api/application_pb";
import * as google_protobuf_empty_pb from "google-protobuf/google/protobuf/empty_pb";
import * as grpc from "@grpc/grpc-js";

interface IApplicationServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  create: grpc.MethodDefinition<api_application_pb.CreateApplicationRequest, api_application_pb.CreateApplicationResponse>;
  get: grpc.MethodDefinition<api_application_pb.GetApplicationRequest, api_application_pb.GetApplicationResponse>;
  update: grpc.MethodDefinition<api_application_pb.UpdateApplicationRequest, google_protobuf_empty_pb.Empty>;
  delete: grpc.MethodDefinition<api_application_pb.DeleteApplicationRequest, google_protobuf_empty_pb.Empty>;
  list: grpc.MethodDefinition<api_application_pb.ListApplicationsRequest, api_application_pb.ListApplicationsResponse>;
  listIntegrations: grpc.MethodDefinition<api_application_pb.ListIntegrationsRequest, api_application_pb.ListIntegrationsResponse>;
  createHttpIntegration: grpc.MethodDefinition<api_application_pb.CreateHttpIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getHttpIntegration: grpc.MethodDefinition<api_application_pb.GetHttpIntegrationRequest, api_application_pb.GetHttpIntegrationResponse>;
  updateHttpIntegration: grpc.MethodDefinition<api_application_pb.UpdateHttpIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteHttpIntegration: grpc.MethodDefinition<api_application_pb.DeleteHttpIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createInfluxDbIntegration: grpc.MethodDefinition<api_application_pb.CreateInfluxDbIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getInfluxDbIntegration: grpc.MethodDefinition<api_application_pb.GetInfluxDbIntegrationRequest, api_application_pb.GetInfluxDbIntegrationResponse>;
  updateInfluxDbIntegration: grpc.MethodDefinition<api_application_pb.UpdateInfluxDbIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteInfluxDbIntegration: grpc.MethodDefinition<api_application_pb.DeleteInfluxDbIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createThingsBoardIntegration: grpc.MethodDefinition<api_application_pb.CreateThingsBoardIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getThingsBoardIntegration: grpc.MethodDefinition<api_application_pb.GetThingsBoardIntegrationRequest, api_application_pb.GetThingsBoardIntegrationResponse>;
  updateThingsBoardIntegration: grpc.MethodDefinition<api_application_pb.UpdateThingsBoardIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteThingsBoardIntegration: grpc.MethodDefinition<api_application_pb.DeleteThingsBoardIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createMyDevicesIntegration: grpc.MethodDefinition<api_application_pb.CreateMyDevicesIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getMyDevicesIntegration: grpc.MethodDefinition<api_application_pb.GetMyDevicesIntegrationRequest, api_application_pb.GetMyDevicesIntegrationResponse>;
  updateMyDevicesIntegration: grpc.MethodDefinition<api_application_pb.UpdateMyDevicesIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteMyDevicesIntegration: grpc.MethodDefinition<api_application_pb.DeleteMyDevicesIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createLoraCloudIntegration: grpc.MethodDefinition<api_application_pb.CreateLoraCloudIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getLoraCloudIntegration: grpc.MethodDefinition<api_application_pb.GetLoraCloudIntegrationRequest, api_application_pb.GetLoraCloudIntegrationResponse>;
  updateLoraCloudIntegration: grpc.MethodDefinition<api_application_pb.UpdateLoraCloudIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteLoraCloudIntegration: grpc.MethodDefinition<api_application_pb.DeleteLoraCloudIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createGcpPubSubIntegration: grpc.MethodDefinition<api_application_pb.CreateGcpPubSubIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getGcpPubSubIntegration: grpc.MethodDefinition<api_application_pb.GetGcpPubSubIntegrationRequest, api_application_pb.GetGcpPubSubIntegrationResponse>;
  updateGcpPubSubIntegration: grpc.MethodDefinition<api_application_pb.UpdateGcpPubSubIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteGcpPubSubIntegration: grpc.MethodDefinition<api_application_pb.DeleteGcpPubSubIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createAwsSnsIntegration: grpc.MethodDefinition<api_application_pb.CreateAwsSnsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getAwsSnsIntegration: grpc.MethodDefinition<api_application_pb.GetAwsSnsIntegrationRequest, api_application_pb.GetAwsSnsIntegrationResponse>;
  updateAwsSnsIntegration: grpc.MethodDefinition<api_application_pb.UpdateAwsSnsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteAwsSnsIntegration: grpc.MethodDefinition<api_application_pb.DeleteAwsSnsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createAzureServiceBusIntegration: grpc.MethodDefinition<api_application_pb.CreateAzureServiceBusIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getAzureServiceBusIntegration: grpc.MethodDefinition<api_application_pb.GetAzureServiceBusIntegrationRequest, api_application_pb.GetAzureServiceBusIntegrationResponse>;
  updateAzureServiceBusIntegration: grpc.MethodDefinition<api_application_pb.UpdateAzureServiceBusIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteAzureServiceBusIntegration: grpc.MethodDefinition<api_application_pb.DeleteAzureServiceBusIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createPilotThingsIntegration: grpc.MethodDefinition<api_application_pb.CreatePilotThingsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getPilotThingsIntegration: grpc.MethodDefinition<api_application_pb.GetPilotThingsIntegrationRequest, api_application_pb.GetPilotThingsIntegrationResponse>;
  updatePilotThingsIntegration: grpc.MethodDefinition<api_application_pb.UpdatePilotThingsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deletePilotThingsIntegration: grpc.MethodDefinition<api_application_pb.DeletePilotThingsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createIftttIntegration: grpc.MethodDefinition<api_application_pb.CreateIftttIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getIftttIntegration: grpc.MethodDefinition<api_application_pb.GetIftttIntegrationRequest, api_application_pb.GetIftttIntegrationResponse>;
  updateIftttIntegration: grpc.MethodDefinition<api_application_pb.UpdateIftttIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteIftttIntegration: grpc.MethodDefinition<api_application_pb.DeleteIftttIntegrationRequest, google_protobuf_empty_pb.Empty>;
  generateMqttIntegrationClientCertificate: grpc.MethodDefinition<api_application_pb.GenerateMqttIntegrationClientCertificateRequest, api_application_pb.GenerateMqttIntegrationClientCertificateResponse>;
}

export const ApplicationServiceService: IApplicationServiceService;

export interface IApplicationServiceServer extends grpc.UntypedServiceImplementation {
  create: grpc.handleUnaryCall<api_application_pb.CreateApplicationRequest, api_application_pb.CreateApplicationResponse>;
  get: grpc.handleUnaryCall<api_application_pb.GetApplicationRequest, api_application_pb.GetApplicationResponse>;
  update: grpc.handleUnaryCall<api_application_pb.UpdateApplicationRequest, google_protobuf_empty_pb.Empty>;
  delete: grpc.handleUnaryCall<api_application_pb.DeleteApplicationRequest, google_protobuf_empty_pb.Empty>;
  list: grpc.handleUnaryCall<api_application_pb.ListApplicationsRequest, api_application_pb.ListApplicationsResponse>;
  listIntegrations: grpc.handleUnaryCall<api_application_pb.ListIntegrationsRequest, api_application_pb.ListIntegrationsResponse>;
  createHttpIntegration: grpc.handleUnaryCall<api_application_pb.CreateHttpIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getHttpIntegration: grpc.handleUnaryCall<api_application_pb.GetHttpIntegrationRequest, api_application_pb.GetHttpIntegrationResponse>;
  updateHttpIntegration: grpc.handleUnaryCall<api_application_pb.UpdateHttpIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteHttpIntegration: grpc.handleUnaryCall<api_application_pb.DeleteHttpIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createInfluxDbIntegration: grpc.handleUnaryCall<api_application_pb.CreateInfluxDbIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getInfluxDbIntegration: grpc.handleUnaryCall<api_application_pb.GetInfluxDbIntegrationRequest, api_application_pb.GetInfluxDbIntegrationResponse>;
  updateInfluxDbIntegration: grpc.handleUnaryCall<api_application_pb.UpdateInfluxDbIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteInfluxDbIntegration: grpc.handleUnaryCall<api_application_pb.DeleteInfluxDbIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createThingsBoardIntegration: grpc.handleUnaryCall<api_application_pb.CreateThingsBoardIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getThingsBoardIntegration: grpc.handleUnaryCall<api_application_pb.GetThingsBoardIntegrationRequest, api_application_pb.GetThingsBoardIntegrationResponse>;
  updateThingsBoardIntegration: grpc.handleUnaryCall<api_application_pb.UpdateThingsBoardIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteThingsBoardIntegration: grpc.handleUnaryCall<api_application_pb.DeleteThingsBoardIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createMyDevicesIntegration: grpc.handleUnaryCall<api_application_pb.CreateMyDevicesIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getMyDevicesIntegration: grpc.handleUnaryCall<api_application_pb.GetMyDevicesIntegrationRequest, api_application_pb.GetMyDevicesIntegrationResponse>;
  updateMyDevicesIntegration: grpc.handleUnaryCall<api_application_pb.UpdateMyDevicesIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteMyDevicesIntegration: grpc.handleUnaryCall<api_application_pb.DeleteMyDevicesIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createLoraCloudIntegration: grpc.handleUnaryCall<api_application_pb.CreateLoraCloudIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getLoraCloudIntegration: grpc.handleUnaryCall<api_application_pb.GetLoraCloudIntegrationRequest, api_application_pb.GetLoraCloudIntegrationResponse>;
  updateLoraCloudIntegration: grpc.handleUnaryCall<api_application_pb.UpdateLoraCloudIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteLoraCloudIntegration: grpc.handleUnaryCall<api_application_pb.DeleteLoraCloudIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createGcpPubSubIntegration: grpc.handleUnaryCall<api_application_pb.CreateGcpPubSubIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getGcpPubSubIntegration: grpc.handleUnaryCall<api_application_pb.GetGcpPubSubIntegrationRequest, api_application_pb.GetGcpPubSubIntegrationResponse>;
  updateGcpPubSubIntegration: grpc.handleUnaryCall<api_application_pb.UpdateGcpPubSubIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteGcpPubSubIntegration: grpc.handleUnaryCall<api_application_pb.DeleteGcpPubSubIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createAwsSnsIntegration: grpc.handleUnaryCall<api_application_pb.CreateAwsSnsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getAwsSnsIntegration: grpc.handleUnaryCall<api_application_pb.GetAwsSnsIntegrationRequest, api_application_pb.GetAwsSnsIntegrationResponse>;
  updateAwsSnsIntegration: grpc.handleUnaryCall<api_application_pb.UpdateAwsSnsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteAwsSnsIntegration: grpc.handleUnaryCall<api_application_pb.DeleteAwsSnsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createAzureServiceBusIntegration: grpc.handleUnaryCall<api_application_pb.CreateAzureServiceBusIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getAzureServiceBusIntegration: grpc.handleUnaryCall<api_application_pb.GetAzureServiceBusIntegrationRequest, api_application_pb.GetAzureServiceBusIntegrationResponse>;
  updateAzureServiceBusIntegration: grpc.handleUnaryCall<api_application_pb.UpdateAzureServiceBusIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteAzureServiceBusIntegration: grpc.handleUnaryCall<api_application_pb.DeleteAzureServiceBusIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createPilotThingsIntegration: grpc.handleUnaryCall<api_application_pb.CreatePilotThingsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getPilotThingsIntegration: grpc.handleUnaryCall<api_application_pb.GetPilotThingsIntegrationRequest, api_application_pb.GetPilotThingsIntegrationResponse>;
  updatePilotThingsIntegration: grpc.handleUnaryCall<api_application_pb.UpdatePilotThingsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deletePilotThingsIntegration: grpc.handleUnaryCall<api_application_pb.DeletePilotThingsIntegrationRequest, google_protobuf_empty_pb.Empty>;
  createIftttIntegration: grpc.handleUnaryCall<api_application_pb.CreateIftttIntegrationRequest, google_protobuf_empty_pb.Empty>;
  getIftttIntegration: grpc.handleUnaryCall<api_application_pb.GetIftttIntegrationRequest, api_application_pb.GetIftttIntegrationResponse>;
  updateIftttIntegration: grpc.handleUnaryCall<api_application_pb.UpdateIftttIntegrationRequest, google_protobuf_empty_pb.Empty>;
  deleteIftttIntegration: grpc.handleUnaryCall<api_application_pb.DeleteIftttIntegrationRequest, google_protobuf_empty_pb.Empty>;
  generateMqttIntegrationClientCertificate: grpc.handleUnaryCall<api_application_pb.GenerateMqttIntegrationClientCertificateRequest, api_application_pb.GenerateMqttIntegrationClientCertificateResponse>;
}

export class ApplicationServiceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  create(argument: api_application_pb.CreateApplicationRequest, callback: grpc.requestCallback<api_application_pb.CreateApplicationResponse>): grpc.ClientUnaryCall;
  create(argument: api_application_pb.CreateApplicationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.CreateApplicationResponse>): grpc.ClientUnaryCall;
  create(argument: api_application_pb.CreateApplicationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.CreateApplicationResponse>): grpc.ClientUnaryCall;
  get(argument: api_application_pb.GetApplicationRequest, callback: grpc.requestCallback<api_application_pb.GetApplicationResponse>): grpc.ClientUnaryCall;
  get(argument: api_application_pb.GetApplicationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetApplicationResponse>): grpc.ClientUnaryCall;
  get(argument: api_application_pb.GetApplicationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetApplicationResponse>): grpc.ClientUnaryCall;
  update(argument: api_application_pb.UpdateApplicationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  update(argument: api_application_pb.UpdateApplicationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  update(argument: api_application_pb.UpdateApplicationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  delete(argument: api_application_pb.DeleteApplicationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  delete(argument: api_application_pb.DeleteApplicationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  delete(argument: api_application_pb.DeleteApplicationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  list(argument: api_application_pb.ListApplicationsRequest, callback: grpc.requestCallback<api_application_pb.ListApplicationsResponse>): grpc.ClientUnaryCall;
  list(argument: api_application_pb.ListApplicationsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.ListApplicationsResponse>): grpc.ClientUnaryCall;
  list(argument: api_application_pb.ListApplicationsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.ListApplicationsResponse>): grpc.ClientUnaryCall;
  listIntegrations(argument: api_application_pb.ListIntegrationsRequest, callback: grpc.requestCallback<api_application_pb.ListIntegrationsResponse>): grpc.ClientUnaryCall;
  listIntegrations(argument: api_application_pb.ListIntegrationsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.ListIntegrationsResponse>): grpc.ClientUnaryCall;
  listIntegrations(argument: api_application_pb.ListIntegrationsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.ListIntegrationsResponse>): grpc.ClientUnaryCall;
  createHttpIntegration(argument: api_application_pb.CreateHttpIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createHttpIntegration(argument: api_application_pb.CreateHttpIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createHttpIntegration(argument: api_application_pb.CreateHttpIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getHttpIntegration(argument: api_application_pb.GetHttpIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetHttpIntegrationResponse>): grpc.ClientUnaryCall;
  getHttpIntegration(argument: api_application_pb.GetHttpIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetHttpIntegrationResponse>): grpc.ClientUnaryCall;
  getHttpIntegration(argument: api_application_pb.GetHttpIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetHttpIntegrationResponse>): grpc.ClientUnaryCall;
  updateHttpIntegration(argument: api_application_pb.UpdateHttpIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateHttpIntegration(argument: api_application_pb.UpdateHttpIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateHttpIntegration(argument: api_application_pb.UpdateHttpIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteHttpIntegration(argument: api_application_pb.DeleteHttpIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteHttpIntegration(argument: api_application_pb.DeleteHttpIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteHttpIntegration(argument: api_application_pb.DeleteHttpIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createInfluxDbIntegration(argument: api_application_pb.CreateInfluxDbIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createInfluxDbIntegration(argument: api_application_pb.CreateInfluxDbIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createInfluxDbIntegration(argument: api_application_pb.CreateInfluxDbIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getInfluxDbIntegration(argument: api_application_pb.GetInfluxDbIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetInfluxDbIntegrationResponse>): grpc.ClientUnaryCall;
  getInfluxDbIntegration(argument: api_application_pb.GetInfluxDbIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetInfluxDbIntegrationResponse>): grpc.ClientUnaryCall;
  getInfluxDbIntegration(argument: api_application_pb.GetInfluxDbIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetInfluxDbIntegrationResponse>): grpc.ClientUnaryCall;
  updateInfluxDbIntegration(argument: api_application_pb.UpdateInfluxDbIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateInfluxDbIntegration(argument: api_application_pb.UpdateInfluxDbIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateInfluxDbIntegration(argument: api_application_pb.UpdateInfluxDbIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteInfluxDbIntegration(argument: api_application_pb.DeleteInfluxDbIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteInfluxDbIntegration(argument: api_application_pb.DeleteInfluxDbIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteInfluxDbIntegration(argument: api_application_pb.DeleteInfluxDbIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createThingsBoardIntegration(argument: api_application_pb.CreateThingsBoardIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createThingsBoardIntegration(argument: api_application_pb.CreateThingsBoardIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createThingsBoardIntegration(argument: api_application_pb.CreateThingsBoardIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getThingsBoardIntegration(argument: api_application_pb.GetThingsBoardIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetThingsBoardIntegrationResponse>): grpc.ClientUnaryCall;
  getThingsBoardIntegration(argument: api_application_pb.GetThingsBoardIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetThingsBoardIntegrationResponse>): grpc.ClientUnaryCall;
  getThingsBoardIntegration(argument: api_application_pb.GetThingsBoardIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetThingsBoardIntegrationResponse>): grpc.ClientUnaryCall;
  updateThingsBoardIntegration(argument: api_application_pb.UpdateThingsBoardIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateThingsBoardIntegration(argument: api_application_pb.UpdateThingsBoardIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateThingsBoardIntegration(argument: api_application_pb.UpdateThingsBoardIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteThingsBoardIntegration(argument: api_application_pb.DeleteThingsBoardIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteThingsBoardIntegration(argument: api_application_pb.DeleteThingsBoardIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteThingsBoardIntegration(argument: api_application_pb.DeleteThingsBoardIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createMyDevicesIntegration(argument: api_application_pb.CreateMyDevicesIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createMyDevicesIntegration(argument: api_application_pb.CreateMyDevicesIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createMyDevicesIntegration(argument: api_application_pb.CreateMyDevicesIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getMyDevicesIntegration(argument: api_application_pb.GetMyDevicesIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetMyDevicesIntegrationResponse>): grpc.ClientUnaryCall;
  getMyDevicesIntegration(argument: api_application_pb.GetMyDevicesIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetMyDevicesIntegrationResponse>): grpc.ClientUnaryCall;
  getMyDevicesIntegration(argument: api_application_pb.GetMyDevicesIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetMyDevicesIntegrationResponse>): grpc.ClientUnaryCall;
  updateMyDevicesIntegration(argument: api_application_pb.UpdateMyDevicesIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateMyDevicesIntegration(argument: api_application_pb.UpdateMyDevicesIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateMyDevicesIntegration(argument: api_application_pb.UpdateMyDevicesIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteMyDevicesIntegration(argument: api_application_pb.DeleteMyDevicesIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteMyDevicesIntegration(argument: api_application_pb.DeleteMyDevicesIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteMyDevicesIntegration(argument: api_application_pb.DeleteMyDevicesIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createLoraCloudIntegration(argument: api_application_pb.CreateLoraCloudIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createLoraCloudIntegration(argument: api_application_pb.CreateLoraCloudIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createLoraCloudIntegration(argument: api_application_pb.CreateLoraCloudIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getLoraCloudIntegration(argument: api_application_pb.GetLoraCloudIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetLoraCloudIntegrationResponse>): grpc.ClientUnaryCall;
  getLoraCloudIntegration(argument: api_application_pb.GetLoraCloudIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetLoraCloudIntegrationResponse>): grpc.ClientUnaryCall;
  getLoraCloudIntegration(argument: api_application_pb.GetLoraCloudIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetLoraCloudIntegrationResponse>): grpc.ClientUnaryCall;
  updateLoraCloudIntegration(argument: api_application_pb.UpdateLoraCloudIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateLoraCloudIntegration(argument: api_application_pb.UpdateLoraCloudIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateLoraCloudIntegration(argument: api_application_pb.UpdateLoraCloudIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteLoraCloudIntegration(argument: api_application_pb.DeleteLoraCloudIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteLoraCloudIntegration(argument: api_application_pb.DeleteLoraCloudIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteLoraCloudIntegration(argument: api_application_pb.DeleteLoraCloudIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createGcpPubSubIntegration(argument: api_application_pb.CreateGcpPubSubIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createGcpPubSubIntegration(argument: api_application_pb.CreateGcpPubSubIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createGcpPubSubIntegration(argument: api_application_pb.CreateGcpPubSubIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getGcpPubSubIntegration(argument: api_application_pb.GetGcpPubSubIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetGcpPubSubIntegrationResponse>): grpc.ClientUnaryCall;
  getGcpPubSubIntegration(argument: api_application_pb.GetGcpPubSubIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetGcpPubSubIntegrationResponse>): grpc.ClientUnaryCall;
  getGcpPubSubIntegration(argument: api_application_pb.GetGcpPubSubIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetGcpPubSubIntegrationResponse>): grpc.ClientUnaryCall;
  updateGcpPubSubIntegration(argument: api_application_pb.UpdateGcpPubSubIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateGcpPubSubIntegration(argument: api_application_pb.UpdateGcpPubSubIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateGcpPubSubIntegration(argument: api_application_pb.UpdateGcpPubSubIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGcpPubSubIntegration(argument: api_application_pb.DeleteGcpPubSubIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGcpPubSubIntegration(argument: api_application_pb.DeleteGcpPubSubIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGcpPubSubIntegration(argument: api_application_pb.DeleteGcpPubSubIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createAwsSnsIntegration(argument: api_application_pb.CreateAwsSnsIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createAwsSnsIntegration(argument: api_application_pb.CreateAwsSnsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createAwsSnsIntegration(argument: api_application_pb.CreateAwsSnsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getAwsSnsIntegration(argument: api_application_pb.GetAwsSnsIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetAwsSnsIntegrationResponse>): grpc.ClientUnaryCall;
  getAwsSnsIntegration(argument: api_application_pb.GetAwsSnsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetAwsSnsIntegrationResponse>): grpc.ClientUnaryCall;
  getAwsSnsIntegration(argument: api_application_pb.GetAwsSnsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetAwsSnsIntegrationResponse>): grpc.ClientUnaryCall;
  updateAwsSnsIntegration(argument: api_application_pb.UpdateAwsSnsIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateAwsSnsIntegration(argument: api_application_pb.UpdateAwsSnsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateAwsSnsIntegration(argument: api_application_pb.UpdateAwsSnsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteAwsSnsIntegration(argument: api_application_pb.DeleteAwsSnsIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteAwsSnsIntegration(argument: api_application_pb.DeleteAwsSnsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteAwsSnsIntegration(argument: api_application_pb.DeleteAwsSnsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createAzureServiceBusIntegration(argument: api_application_pb.CreateAzureServiceBusIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createAzureServiceBusIntegration(argument: api_application_pb.CreateAzureServiceBusIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createAzureServiceBusIntegration(argument: api_application_pb.CreateAzureServiceBusIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getAzureServiceBusIntegration(argument: api_application_pb.GetAzureServiceBusIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetAzureServiceBusIntegrationResponse>): grpc.ClientUnaryCall;
  getAzureServiceBusIntegration(argument: api_application_pb.GetAzureServiceBusIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetAzureServiceBusIntegrationResponse>): grpc.ClientUnaryCall;
  getAzureServiceBusIntegration(argument: api_application_pb.GetAzureServiceBusIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetAzureServiceBusIntegrationResponse>): grpc.ClientUnaryCall;
  updateAzureServiceBusIntegration(argument: api_application_pb.UpdateAzureServiceBusIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateAzureServiceBusIntegration(argument: api_application_pb.UpdateAzureServiceBusIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateAzureServiceBusIntegration(argument: api_application_pb.UpdateAzureServiceBusIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteAzureServiceBusIntegration(argument: api_application_pb.DeleteAzureServiceBusIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteAzureServiceBusIntegration(argument: api_application_pb.DeleteAzureServiceBusIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteAzureServiceBusIntegration(argument: api_application_pb.DeleteAzureServiceBusIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createPilotThingsIntegration(argument: api_application_pb.CreatePilotThingsIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createPilotThingsIntegration(argument: api_application_pb.CreatePilotThingsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createPilotThingsIntegration(argument: api_application_pb.CreatePilotThingsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getPilotThingsIntegration(argument: api_application_pb.GetPilotThingsIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetPilotThingsIntegrationResponse>): grpc.ClientUnaryCall;
  getPilotThingsIntegration(argument: api_application_pb.GetPilotThingsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetPilotThingsIntegrationResponse>): grpc.ClientUnaryCall;
  getPilotThingsIntegration(argument: api_application_pb.GetPilotThingsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetPilotThingsIntegrationResponse>): grpc.ClientUnaryCall;
  updatePilotThingsIntegration(argument: api_application_pb.UpdatePilotThingsIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updatePilotThingsIntegration(argument: api_application_pb.UpdatePilotThingsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updatePilotThingsIntegration(argument: api_application_pb.UpdatePilotThingsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deletePilotThingsIntegration(argument: api_application_pb.DeletePilotThingsIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deletePilotThingsIntegration(argument: api_application_pb.DeletePilotThingsIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deletePilotThingsIntegration(argument: api_application_pb.DeletePilotThingsIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createIftttIntegration(argument: api_application_pb.CreateIftttIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createIftttIntegration(argument: api_application_pb.CreateIftttIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createIftttIntegration(argument: api_application_pb.CreateIftttIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getIftttIntegration(argument: api_application_pb.GetIftttIntegrationRequest, callback: grpc.requestCallback<api_application_pb.GetIftttIntegrationResponse>): grpc.ClientUnaryCall;
  getIftttIntegration(argument: api_application_pb.GetIftttIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetIftttIntegrationResponse>): grpc.ClientUnaryCall;
  getIftttIntegration(argument: api_application_pb.GetIftttIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GetIftttIntegrationResponse>): grpc.ClientUnaryCall;
  updateIftttIntegration(argument: api_application_pb.UpdateIftttIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateIftttIntegration(argument: api_application_pb.UpdateIftttIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateIftttIntegration(argument: api_application_pb.UpdateIftttIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteIftttIntegration(argument: api_application_pb.DeleteIftttIntegrationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteIftttIntegration(argument: api_application_pb.DeleteIftttIntegrationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteIftttIntegration(argument: api_application_pb.DeleteIftttIntegrationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  generateMqttIntegrationClientCertificate(argument: api_application_pb.GenerateMqttIntegrationClientCertificateRequest, callback: grpc.requestCallback<api_application_pb.GenerateMqttIntegrationClientCertificateResponse>): grpc.ClientUnaryCall;
  generateMqttIntegrationClientCertificate(argument: api_application_pb.GenerateMqttIntegrationClientCertificateRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GenerateMqttIntegrationClientCertificateResponse>): grpc.ClientUnaryCall;
  generateMqttIntegrationClientCertificate(argument: api_application_pb.GenerateMqttIntegrationClientCertificateRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<api_application_pb.GenerateMqttIntegrationClientCertificateResponse>): grpc.ClientUnaryCall;
}
