FROM node:19

ENV PROJECT_PATH=/chirpstack/api
RUN apt update && apt install -y protobuf-compiler libprotobuf-dev git bash

RUN git clone https://github.com/googleapis/googleapis.git /googleapis

ADD https://github.com/grpc/grpc-web/releases/download/1.4.2/protoc-gen-grpc-web-1.4.2-linux-x86_64 /usr/bin/protoc-gen-grpc-web
RUN chmod +x /usr/bin/protoc-gen-grpc-web

RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH
