FROM rust:1.65

ENV PROJECT_PATH=/chirpstack/api
RUN apt-get update && \
	apt-get install -y make cmake git bash protobuf-compiler && \
	apt-get clean

RUN git clone https://github.com/googleapis/googleapis.git /googleapis

RUN rustup component add rustfmt

RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH
